INSERT INTO genres (genre_name) VALUES
('Americana'),
('Ballad'),
('Big Band'),
('Blues'),
('Bolero'),
('Calypso'),
('Chicano Rock'),
('Christian'),
('Christmas'),
('Country'),
('Doo Wop'),
('Folk'),
('Gospel'),
('Halloween'),
('Honky Tonk'),
('Hymn'),
('Irish'),
('Irish Folk'),
('Jazz'),
('Latin Ballad'),
('March'),
('Musical Theater'),
('Patriotic'),
('Polka'),
('Pop'),
('Protest'),
('Rhythm & Blues'),
('Rock & Roll'),
('Rockabilly'),
('Spiritual'),
('Standards'),
('Swing'),
('Traditional'),
('Western');
