INSERT INTO genres (genre_name) VALUES
('Acoustic Rock'),
('Alternative Rock'),
('Americana'),
('Ballad'),
('Baroque Pop'),
('Big Band'),
('Blues'),
('Blues Rock'),
('Bolero'),
('Britpop'),
('Calypso'),
('Chicano Rock'),
('Christian'),
('Christian Rock'),
('Christmas'),
('Classic Rock'),
('Classical'),
('Contemporary Christian'),
('Country'),
('Country Pop'),
('Country Rock'),
('Disco'),
('Doo Wop'),
('Easy Listening'),
('EDM'),
('Experimental'),
('Folk'),
('Folk Rock'),
('Funk'),
('Funk Rock'),
('Garage Rock'),
('Girl Group'),
('Glam Rock'),
('Gospel'),
('Halloween'),
('Hard Rock'),
('Heavy Metal'),
('Hip Hop'),
('Honky Tonk'),
('Hymn'),
('Indie Folk'),
('Indie Pop'),
('Irish'),
('Irish Folk'),
('Jazz'),
('Latin Ballad'),
('March'),
('Motown'),
('Musical Theater'),
('Outlaw Country'),
('Patriotic'),
('Polka'),
('Pop'),
('Pop Punk'),
('Pop Rock'),
('Progressive Rock'),
('Protest'),
('Psychedelic Pop'),
('Psychedelic Rock'),
('Reggae'),
('Rhythm & Blues'),
('Rock'),
('Rock & Roll'),
('Rockabilly'),
('Showtune'),
('Singer-Songwriter'),
('Soft Rock'),
('Soul'),
('Southern Rock'),
('Spiritual'),
('Standards'),
('Surf Rock'),
('Swing'),
('Traditional'),
('Tropical Rock'),
('Western');

